name: Build and deploy
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Login to Docker Registry
        run: echo "${{ secrets.GHCR }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Build and push Docker image to GitHub Packages
        run: |
          export DOCKER_IMAGE_NAME=docker.pkg.github.com/${{ github.repository }}/my-image
          export DOCKER_IMAGE_TAG=${{ github.sha }}
          docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
          docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - name: Deploy to production
        env:
          PRODUCTION_SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
        run: |
          ssh user@${{ env.PRODUCTION_SERVER_IP }} "docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GHCR }} && docker pull docker.pkg.github.com/${{ github.repository }}/my-image:${{ github.sha }} && docker run -p 8080:8080 -d docker.pkg.github.com/${{ github.repository }}/my-image:${{ github.sha }}"
