name: Build and distribute
on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        uses: docker://docker.pkg.github.com/actions/github-script:latest
        with:
          args: |
            const { execSync } = require('child_process');
            const version = execSync('echo $GITHUB_SHA').toString().trim();
            execSync(`./gradlew bootJar -Pversion=${version}`);
            execSync(`echo ${{ secrets.GHCR }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin`);
            execSync(`docker build -t docker.pkg.github.com/${{ github.repository }}/my-image:${version} .`);
            execSync(`docker push docker.pkg.github.com/${{ github.repository }}/my-image:${version}`);

      - name: Download Docker image
        uses: docker://docker.pkg.github.com/${{ github.repository }}/my-image:${{ github.sha }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}

      - name: Deploy Docker image
        uses: docker://docker.pkg.github.com/${{ github.repository }}/my-image:${{ github.sha }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}
